### ISSUE TITLE
Consider revising choice of scopes

### ISSUE THREAD

**Issue by Alhadis** [hexpunK/language-patch#2]
Hey,

I noticed the package is using `invalid.deprecated.line.addition.patch` and `invalid.illegal.file.subtraction.patch` to highlight added or removed lines. You might consider using the scope-names that the [`language-diff`](https://atom.io/packages/language-diff) package uses ([example](https://github.com/miketheman/language-diff/blob/master/grammars/diff.cson#L91-L97)).

It looks absolutely superb in Atom, and I'm guessing most well-established syntax themes already support diff elements in their styling:

<img src="https://cloud.githubusercontent.com/assets/2346707/16127377/9461f1d0-343f-11e6-8e51-c2e1e26a1c17.png" width="590" alt="Figure 1" />

FYI, that package I linked to also supports `.patch` files, which're essentially the same format as a `.diff`.

**Comment by hexpunK** [comment]
Ah excellent. At the time I made this I wasn't really super aware of what scopes were available to be honest! What with it being baby's first package essentially.

Which also explains the redundancy! There's no real reason for the package to exist other than me making it on a whim. I expect language-diff does a better job in general.

Though I will look at those scopes, if they look better and are generally more compatible then it's worth my time to move over to them.

**Comment by Alhadis** [comment]
Well... I'm not entirely sure you'll top that package, since it was converted from the [TextMate bundle](https://github.com/textmate/diff.tmbundle) for Diffs. TextMate actually invented the grammar format that Atom uses, and it's even the [same one used by GitHub](https://github.com/camelguo/linux-2.6-trimedia/blob/ccb6b544486965649d0344b4d7f934155f38e6c8/patches/mdsmbe.patch).

So, uh... dunno what to say here, mate... but in all honesty, I'm not gonna lie to ya: the package is pretty much doing everything the package could possibly be able to.

**Comment by hexpunK** [comment]
Yeah...maintaining this thing by this point is mostly just a "why not" to be honest. I've been considering just removing it for a while as even I stopped using it when I actually bothered to find language-diff. The fact it even has (possible) users still makes me chuckle a bit when language-diff is technically superior in every way!

**Comment by Alhadis** [comment]
Heh, I think it all comes down to what people search for. Anybody installing this package probably searched for "language patch", while others searched for "language diff".

Don't feel bad though, mate, you put effort into learning how to write and publish a grammar, which is more than what can be said for a lot of users who published their first language-packages (many of whom just convert it from an existing Sublime Text or TextMate grammar).

Proud to say I'm an exception, but I'm a meticulous prick with no life and an unhealthy obsession with regular expressions.

**Comment by hexpunK** [comment]
Regex is love, regex is life.

I'll tinker with the scopes anyhow, see if it looks correct under a few styles and push that change out. Might as well do something with my time haha.

**Comment by hexpunK** [comment]
The commit;
https://github.com/hexpunK/language-patch/commit/dc9713c2123266038f0d6a0921b2741a759e2992

Contains the changes to the scopes as suggested, along with a small change to the regexp in an attempt to lower duplication a bit.
